FROM nikolaik/python-nodejs:python3.8-nodejs12
MAINTAINER rubi1541 <rubi1541@naver.com>

WORKDIR /usr/app

# supervisor 설치
# 참고: https://riptutorial.com/de/docker/example/14132/dockerfile-plus-supervisord-conf
# 

# COPY package.json .
# RUN npm install --quiet